ARG IMAGE_VERSION=edge
FROM alpine:${IMAGE_VERSION}
LABEL maintainer="Björn Busse <bj.rn@baerlin.eu>"
LABEL org.opencontainers.image.source https://github.com/bbusse/mdns-discover-build

ENV ARCH="x86_64" \
    USER="build" \
    PACKAGES="git xz" \
    PATH="/usr/local/go/bin:${PATH}"

COPY --from=golang:1.20-alpine /usr/local/go/ /usr/local/go/

# Add application user and application
RUN addgroup -S $USER && adduser -S $USER -G $USER \
    && apk add --no-cache ${PACKAGES} \
    && cd /tmp && git clone --depth 1 https://github.com/bbusse/mdns-discover \
    && cd /tmp/mdns-discover && go build \
    && cp mdns-discover mdns-discover-${TARGETOS}-${TARGETARCH}-${TARGETVARIANT} \
    && ls -al \
    && xz mdns-discover-linux-amd64
