name: Build and release container

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-and-release-container:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push container to ghcr
      id: build_container
      uses: docker/build-push-action@v3
      with:
        platforms: linux/arm64, linux/amd64, linux/386
        push: true
        file: Containerfile-build
        tags: ghcr.io/bbusse/mdns-discover-build:latest

    - name: Build and push container to ghcr
      id: container
      uses: docker/build-push-action@v3
      with:
        platforms: linux/arm64, linux/amd64, linux/386
        push: true
        file: Containerfile
        tags: ghcr.io/bbusse/mdns-discover:latest

    - name: Image digest
      run: |
        echo ${{ steps.build_container.outputs.digest }} \
        echo ${{ steps.container.outputs.digest }}
