name: Build and push container

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  container-build-push:
    uses: bbusse/github-workflows/.github/workflows/container-build-push.yaml@dev
    with:
      image_name: 'mdns-discover'
      image_repository: 'ghcr.io/bbusse'
      container_registry: 'ghcr'
      container_push_to_registry: true
