name: Build and release FreeBSD

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-freebsd:
    runs-on: macos-12
    name: Build on FreeBSD
    steps:
      - uses: actions/checkout@v3.3.0
      - name: FreeBSD Build
        uses: vmactions/freebsd-vm@v0.3.0
        id: build
        with:
          usesh: true
          prepare: |
            pkg install -y curl go

          run: |
            freebsd-version
            pwd
            ls -lah
            go build
            tar -cJvf mdns-discover-freebsd-amd64-latest.tar.xz mdns-discover
            ls -lah

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mdns-discover-freebsd
          path: mdns-discover-freebsd-amd64-latest.tar.xz
